### ISSUE TITLE
Reuse Credential Offer identifier from metadata in `authorization_details` Authorization Request parameter

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VCI#102]
During IETF Prague, discussion came up to reuse the identifier used in Credential Offer that was introduced with #86 in the Authorization Request with authorization_details, e.g.:

```
[
   {
      "type": "openid_credential",
      "credential_description": "UniversityDegreeCredential"
   }
]
```

**Comment by tlodderstedt** [comment]
I think this makes sense. We should have done this when we introduced the credential identifiers.

**Comment by markuskreusch** [comment]
From an implementation perspective this seems reasonable. I so far preferred the scope over the authorization details because it was a single identifier that could reference the credential in the metadata. With this approach the same is possible but in a more concise way and without the need for a scope per credential.

Especially with SD-JWTs there could be some confusion of the type used here for the authorization_details with the credentials_supported array in the issuer metadata, where each supported SD-JWT has a type as well. As far as I understood this will be called vct in the future and thus be distinguishable from each other. JWT VCs have types as well. The spec could stress, that this is a different type.

**Comment by Sakurann** [comment]
agreed this makes sense. looks like ready for PR

**Comment by paulbastian** [comment]
@tlodderstedt @Sakurann so you see this as an optional alternative or the only way to use authorisation details?
