### ISSUE TITLE
Gender-neutral language

### ISSUE THREAD

**Issue by ju-cu** [openid/OpenID4VCI#123]
Make sure to use gender-neutral language throughout the spec, i.e. remove pronouns like "he"/ "his" or "she"/"her". Consider using "they" instead or refer to roles like "End-User".

**Comment by Sakurann** [comment]
Great suggestion! Would you be able to do a PR, @ju-cu?

**Comment by ju-cu** [comment]
Sure, I can help out with that!

**Comment by selfissued** [comment]
My request would be to not use "they" when the reference of the pronoun is singular, since that would be grammatically incorrect.  "They" is a plural pronoun.  It's jarring to hear it misused.

I do support removing "he" and "she".  The way to do that in a grammatically correct manner is to replace "he" or "she" with the actual party being referenced.  For instance, many of these uses can be replaced by "the End-User".

**Comment by peppelinux** [comment]
@ju-cu while my hands was on the keyboard, this PR https://github.com/openid/OpenID4VCI/pull/143 started out with a certain naturalness
