### ISSUE TITLE
Move Use Cases Appendix before Acknowledgements and Notices

### ISSUE THREAD

**Issue by selfissued** [openid/OpenID4VCI#189]
Since we're moving the content-full Appendix E up in #171 it occurs to me that we should move the other content-full Appendix D (Use Cases) ahead of the Acknowledgements and Notices.

I think we should do this immediately after #171 is merged, and do so in a PR that does nothing but this.  When we move it, we should make no changes to the text.  Hopefully we can gather approvals to do this in advance.

**Comment by selfissued** [comment]
Of course, it would be helpful if we were to merge #190 and #174 before moving the Use Cases, since they make changes to it.

**Comment by Sakurann** [comment]
I am not sure I agree with the proposed change. We are not moving appendix E because it is contentful but because it is what we want to read the readers first. After that I would prefer them to read acknowledgements and notices section as those are quite important. We moved use cases to the appendix because this space evolved so much that people reading the spec already have use cases in mind.

**Comment by Sakurann** [comment]
there does not seem to be clear rule. in IETF, notices are in the beginning, in OIDC, they are in the appendix. acknowledgements do seem to be the last. happy to review the PR, if someone does it.
