### ISSUE TITLE
Does the Deferred Endpoint needs a transaction_id?

### ISSUE THREAD

**Issue by decentralgabe** [openid/OpenID4VCI#225]
The [Deferred Credential Request](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-9.1) requires a `transaction_id`:

> transaction_id: REQUIRED. String identifying a Deferred Issuance transaction.

However, the credential a client is requesting information about should be bound to the auth token they send along with the deferred credential request. Is there a reason to duplicate the information in both the auth token and the transaction ID or could we simplify the request?

**Comment by Sakurann** [comment]
Yes, `transaction_id` is needed because there is no guarantee that the access token contains the information which credential is being issued and the same access token can be valid for the issuance of multiple credentials.
For the first point, Especially when `scope` is being used to issue credentials. For example, in our implementation, the same scope value will be used for multiple credential_configuration_ids, and only scope will be included in the access token (because of the limitations of reusing an existing big AS in production). so transaction_id becomes the only way to identify a specific credential. 
For the second point, (though this part probably needs to be discussed more), when multiple credentials are being issued in the same session using the same access token, transaction_id helps to determine which credential is being issued.

**Comment by jogu** [comment]
Agree with Kristina; `transaction_id` gives the issuer a way to understand what is going on without storing additional state itself. The transaction id is an identifier for an asynchronous process that's going on somewhere in the issuer's backend and there may be more than one of those processes going on for any particular access token.

**Comment by decentralgabe** [comment]
Makes sense thanks for the answers!
