### ISSUE TITLE
Description of `authorization_details` in section 6.2 is confusing

### ISSUE THREAD

**Issue by gffletch** [openid/OpenID4VCI#298]
Instead of using `MUST NOT`, I'd make it a positive statement.

REQUIRED. An `authorization_details` response claim MUST only be returned if an `authorization_details` parameter is present in the request. ...

**Comment by Sakurann** [comment]
the current text is what we have to use because we can't use `CONDITIONAL`. the text suggested in the issue with just `REQUIRED. ` would be wrong here, because there are cases when this parameter is not present in the token response (when `authorization_details` was not present in the request). i think the current text is the best we can do.

**Comment by Sakurann** [comment]
will close unless hear specific proposals/objections in a week.
