### ISSUE TITLE
Credential Issuer Metadata - nested objects & display properties

### ISSUE THREAD

**Issue by sschulz-t** [openid/OpenID4VCI#315]
I was wondering how to interpret the definition of [Credential Issuer Metadata](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-issuer-metadata-6):

Specifically the sentence 
>  ...the **most deeply nested** value MAY be an object that includes the following parameters defined by this specification:

Does this suggest that we only support display properties at the leaf nodes?

Or is it possible to have display properties at all levels? 

E.g. is this a valid definition?
```
{
   ...
    "claims": {
        "address" : {
            "display" : [
                { "name": "Adresse",  "locale": "de" },
                { "name": "Address", "locale": "en" }
            ],
            "street" : {
                "display" : [
                    { "name": "Strasse", "locale": "de"},
                    { "name": "Street", "locale": "en" }
                ]
            }
        }
    }
}
```

If this is valid, how would i handle credentials that have a "display" property on their own? e.g.
```
...
  "property1" : {
     ...
     "display": false,
  }

```

**Comment by paulbastian** [comment]
The problem is being tackled in https://github.com/openid/OpenID4VCI/pull/276 already

**Comment by Sakurann** [comment]
to Paul's point, right now, only display properties at the leaf nodes are supported, so the example you are providing is not defined by the specification right now. The issue was raised in #276, we were discussion solutions, but in the end decided not to introduce this breaking change before VCI ID-1. Please continue this discussion in #276, but would like your feedback how big of a problem it is for you as an implementer the inability to express display properties at all levels for nested claims?

**Comment by sschulz-t** [comment]
Thanks, i see. You switched to use path values. I will post a reply to [mickrau](https://github.com/mickrau) [on Feb 21](https://github.com/openid/OpenID4VCI/pull/276#discussion_r1497169863) and continue there.
